# *********************************
# * Charba Travis-CI build script *
# * Copyright © 2019 pepstock.org *
# *********************************

#
# CONFIGURATION
#
# define the language
language: java
# enable container-based build (faster), insted of vm build
sudo: false
# cache the Ivy cache directory to avoid download dependencies on each build
cache:
   directories:
   - ~/.ivy2
# specify the JDKs 
jdk:
   - oraclejdk8
# specify the brances to build from
branches:
   only:
     - cuc
#
# BUILD phase
#
# download Ivy, if needed
before_install: ant ivyInit
# list the content of Ivy cache dir BEFORE 
before_script: sh ./scripts/before_script.sh
# run the ant main target
script: ant build-bin
# list the content of Ivy cache dir AFTER
after_script: ls -R ~/.ivy2 
#
# DEPLOY phase
#
deploy:
   # do NOT clean the results
   skip_cleanup: true
#
# NOTIFICATIONS
#
# notify the team on failures (successes are not notified)
#notifications:
#   email:
#      recipients:
#      - team@pepstock.org
#   on_success: never
#   on_failure: always
